version: '3.8'

services:
  dev-db:
    container_name: birdy_task_dev
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: birdy_task_dev
    ports:
      - '5434:5432'
  test-db:
    container_name: birdy_task_test
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: birdy_task_test
    ports:
      - '5435:5432'
  api:
    depends_on:
      - dev-db
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://admin:password@dev-db:5432/birdy_task_dev?schema=public'
    # Run a command against the development stage of the image
    command: pnpm start:dev:migrate
    ports:
      - 3000:3000
