version: '3.8'

services:
  dev-db:
    container_name: birdy_task_dev
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: birdy_task_dev
    ports:
      - '5434:5432'
  test-db:
    container_name: birdy_task_test
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: birdy_task_test
    ports:
      - '5435:5432'
