name: Azure Web App Deploy

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
  
env:
  VITE_SWAGGER_URL: ${{ secrets.VITE_SWAGGER_URL }}
  VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          path: frontend
          version: 9
          
          

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          path: frontend
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies and build
        working-directory: frontend
        run: |
            pnpm install
            pnpm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: birdy-task
          path: dist 
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: birdy-task

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: birdy-task
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .